### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by cosminalco** [auchenberg/vscode-browser-preview#113]
I switched to dark theme in Windows 10. Google Chrome displays with the dark theme, Google Chrome Debugger also displays with the dark theme. Will it be possible also for Browser Preview to have a dark theme?

In the screenshot bellow it can be seen that the address bar is a little to aggressive with the white color. Also when refreshing the background is white for a moment. A setting somewhere, I'll be happy, if possible.

![theme](https://user-images.githubusercontent.com/42435633/60045113-afe49a00-96cc-11e9-98c7-5f609acceb9b.png)

**Comment by auchenberg** [comment]
Great idea. Should be easy to land some CSS tweaks in https://github.com/auchenberg/vscode-browser-preview/blob/master/src/components/toolbar/toolbar.css

**Comment by cosminalco** [comment]
Thinking about it, probably a better idea would be to inherit the colors from the current VS Code theme . 

Looks like these three are the best candidates to import the colors from: `input.background` , `input.foreground`, `input.border`

Then something like this will also update the Browser Preview colors:
```json
"workbench.colorCustomizations": {
    "[current theme]": {
       "input.background": "black",
       "input.foreground": "white",
       "input.border": "gray"
    }
```

**Comment by auchenberg** [comment]
VS Code colors are available as CSS variables, so this should be quite easy to add. https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content

**Comment by cosminalco** [comment]
It looks like this four will do the job: `input.background` , `input.foreground`, `input.border`, `panel.background`

![Annotation 2019-06-25 011100](https://user-images.githubusercontent.com/42435633/60055497-7d479b00-96e6-11e9-92f2-2774a4c23a57.png)

**Comment by cosminalco** [comment]
That much I could do:
![Annotation 2019-06-25 160159](https://user-images.githubusercontent.com/42435633/60100599-b9204600-9762-11e9-966a-85451ff07f89.png)
I played around in build/static/css/main....css. I could't change the white background and the buttons color

```css
.toolbar{
    background:var(--vscode-panel-background)
}
button{
    color:var(--vscode-input-foreground)
}
.urlbar{
    background:var(--vscode-input-background);
    border:1px solid var(--vscode-input-border);
    color:var(--vscode-input-foreground)
}
.urlbar input{
    color:var(--vscode-input-foreground);
    background-color:var(--vscode-input-background)
}
.viewport{
    background:var(--vscode-panel-background)
}
```

I know there are also some hovers, active, context menu, responsive panel I didn't touch.
